### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Subnotic** [LatvianModder/FTBLib#15]
FTBLib-1.7.10-1.0.17.2
FTBUtilities-1.7.10-1.0.17.1

```
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.ConcurrentModificationException
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:29)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:265)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[09:07:45] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at java.lang.Thread.run(Thread.java:745)
```

This happens randomly while the server is running but doesn't crash it. The only mod I have updated is FTBL and FTBU then this occurred. It doesn't seem to be anything fatal just spams it in the console. This same issue also happened while Sevadus was streaming but randomly stopped.

**Comment by LatvianModder** [comment]
So this just prints in console, but doesnt crash server?

**Comment by Subnotic** [comment]
Yes, it just throws that in console right after server start but I haven't seen it much since, it's weird. I'm pretty sure I don't have any other chunk loaders in those areas either.

**Comment by smisch** [comment]
Also happens on the current version of Infinity Evolved (expert mode) version 2.3.5

FTBLib-1.7.10-1.0.14.3
FTBUtilities-1.7.10-1.0.14.2

Exception occurs every 3 hours approximately. We're using both FTBU and Railcraft (1.7.10-9.8.0.0) World Anchors for chunk loading the same areas. 
 
````
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.ConcurrentModificationException
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:29)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:265)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[05:45:33] [File IO Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
````
