### ISSUE TITLE
[1.9.4] FTB Unstable 4.0.9 - Frequent server crashes on player logout

### ISSUE THREAD

**Issue by cri5ti** [LatvianModder/FTBLib#23]
```
java.lang.NullPointerException: Exception in server tick loop
	at com.feed_the_beast.ftbl.FTBLibEventHandler.onPlayerLoggedOut(FTBLibEventHandler.java:105)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_204_FTBLibEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:563)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:379)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:806)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

```

Complete crashlog: https://gist.github.com/cri5ti/d57e1f33cd490cbb168c1fb89ae44635

**Comment by knoxz** [comment]
same issue here.
http://pastebin.com/W3HrPWmq

**Comment by cri5ti** [comment]
I've done a quick and dirty fix on this and added an extra change here:

https://github.com/LatvianModder/FTBLib/blob/1.9/src/main/java/com/feed_the_beast/ftbl/FTBLibEventHandler.java#L103

```
if(e.player instanceof EntityPlayerMP)
{
    ForgePlayerMP p = ForgeWorldMP.inst.getPlayer(e.player);
    if (p != null) p.onLoggedOut();
}
```

Probably even uncompleted connections get the event, though I don't know anything about Forge to see the implications of this. Previously I was getting a crash every half an hour. With this fix I've been going for a few hours without a crash.

**Comment by LatvianModder** [comment]
Fixed in pre2
