### ISSUE TITLE
Crash on player logout

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBLib#28]
`java.lang.NullPointerException: Exception in server tick loop
	at com.feed_the_beast.ftbl.FTBLibEventHandler.onPlayerLoggedOut(FTBLibEventHandler.java:105)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_266_FTBLibEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:570)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:379)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:804)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)`

Example of full crash: http://pastebin.com/raw/RU3HKb5V

**Comment by kreezxil** [comment]
Confirmed on 1.10.2 dedicated server build 2018

Server Crash Report: https://gist.github.com/6c5906cc07a5da3beacb091660416c8a

Server FML Latest: https://gist.github.com/1f49e1f01c31e6e39a0156d0da3161cd

**Comment by Alleluid** [comment]
Can also confirm
http://pastebin.com/bBhU1Kf5
