### ISSUE TITLE
[1.10.2] NullPointerException on server login

### ISSUE THREAD

**Issue by MrNinja93** [LatvianModder/FTBLib#53]
Playing on FTB Beyond trying to track down a bug some players have been experiencing and come across this NPE in the log's, can't find any mention of it being reported previously, seems to occur on every login to server doesn't appear to cause any issues (Though there is a random time-out bug afflicting the server, may be related) 

**Mods:-**
FTBLib- 3.5.3
Forge 12.18.3.2254

**Full logs:-** https://gist.github.com/MrNinja93/c58b8ec9df3b9abcb8df544379e7c813

**Relevant stacktrace:-**
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.feed_the_beast.ftbl.lib.BroadcastSender.func_145747_a(BroadcastSender.java:33) ~[BroadcastSender.class:?]
	at com.feed_the_beast.ftbl.lib.LangKey.printChat(LangKey.java:36) ~[LangKey.class:?]
	at com.feed_the_beast.ftbl.api_impl.FTBLibAPI_Impl.reload(FTBLibAPI_Impl.java:154) ~[FTBLibAPI_Impl.class:?]
	at com.feed_the_beast.ftbl.net.MessageLogin.onMessage(MessageLogin.java:161) ~[MessageLogin.class:?]
	at com.feed_the_beast.ftbl.net.MessageLogin.onMessage(MessageLogin.java:35) ~[MessageLogin.class:?]
	at com.feed_the_beast.ftbl.client.FTBLibModClient.lambda$handleClientMessage$2(FTBLibModClient.java:250) ~[FTBLibModClient.class:?]
	at com.feed_the_beast.ftbl.client.FTBLibModClient$$Lambda$1850/517044205.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]```

**Comment by LatvianModder** [comment]
3.5.4 should fix the problem
