### ISSUE TITLE
Cannot load FTBLib, even when it is the only mod being loaded in Forge.

### ISSUE THREAD

**Issue by V3xatious** [LatvianModder/FTBLib#61]
I have tried many versions of forge for 1.12, and no matter what I do, even with FTBLib being the only mod being loaded, this error is given.

**The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBLib (ftbl)**

I am unsure as to why.
For now, I have removed FTBLib from my server and client files that way myself and others can continue without waiting, but I figured I'd let you know! Or, it's something I'm doing and have no idea...Which, if that's it, I apologize for wasting your time.

**Comment by Protheus** [comment]
Think it is the same issue but with more information. The game starts and after 5s, it gives the crash log. This happens with and without Foamfix.

MC: 1.12
Forge: 2387 (Rec)
FTBLib-4.0.2

**Pastebin**: https://pastebin.com/05tMdAQg
**Log**: https://pastebin.com/k3FJxuKM

**Short error**:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBLib (ftbl)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
    at com.feed_the_beast.ftbl.FTBLibMod.onPreInit(FTBLibMod.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.IForgeRegistryEntry
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 41 more
Caused by: java.lang.NullPointerException

**Comment by HenrikoMagnifico** [comment]
I am also having this issue... wonder what causes it

**Comment by Hokmun** [comment]
Same problem

**Comment by HenrikoMagnifico** [comment]
I will try and see if reverting to an older version will solve the problem.

**Comment by TekuSP** [comment]
http://paste.feed-the-beast.com/view/9d4c4d52 Same problem.

**Comment by V3xatious** [comment]
I would like to mention to some of the people posting; I see other plugins/mods attempting to be loaded. I am specifically talking about only loading up FTBLib, alone, and it throwing an error at me.  (Tried first with FTBUtilities, then just FTBLib, error both ways.)

Henriko; You have other mods;
TekuSP; You have other mods;
Protheus; You have other mods;

While i'm not saying it's not the same issue, you are trying to load up more than just FTBLib, which, as I titled this error, as ONLY trying to load up FTBLib.

**Comment by Shadows-of-Fire** [comment]
lat pls update forge

**Comment by HenrikoMagnifico** [comment]
The crash still occurs on the latest version of Forge 1.12.2389. Using FTBLib only on 4.0.2. Crash log: https://pastebin.com/6Vtbh3NP

**Comment by V3xatious** [comment]
Can confirm the crash is the same on the recent beta version of 2390 of Forge as well.

**Comment by HenrikoMagnifico** [comment]
The crash is still occuring on forge-1.12-14.21.1.2395.

**Comment by V3xatious** [comment]
Confirmed on 2396 Forge.

**Comment by Shadows-of-Fire** [comment]
Stop posting comments in this issue, this will be present on all versions of forge from 2348 and onwards.

**Comment by V3xatious** [comment]
@Shadows-of-Fire Has this been posted somewhere that no future versions of Forge will fix this in 1.12?

**Comment by Shadows-of-Fire** [comment]
This is not a forge issue.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/481#issuecomment-313076124

**Comment by V3xatious** [comment]
I have it running on client and server. Well, the server booted at least. The only issue is that when I hit "Server Info" it says "An unknown error occurred while attempting to perform this command."

I'm not sure if that means the server side isn't collecting server information or some sort of interruption in between.

**Comment by V3xatious** [comment]
So...should I make a new post about what I posted above?

**Comment by LatvianModder** [comment]
Update FTBLib to 4.0.4 and try again, could be related to the client crash

**Comment by V3xatious** [comment]
I have already mentioned that I have updated both .jar files to 4.0.4 on both client and server with the error still appearing.
It's running 2387 Forge, so I'm not sure if updating to 2397 would fix it?

**Comment by LatvianModder** [comment]
Try that. Anyway, this is no longer related to original issue

**Comment by sperly** [comment]
Running good  with 4.0.4 on Forge 2400!
